name: FreeBSD

on:
  push:
    branches:
    - freebsd-fix-attempt
  pull_request:
    branches:
    - deactivated

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: macos-12
    name: FreeBSD build

    steps:
    - uses: actions/checkout@v2
    - name: Compile in FreeBSD VM
      id: build
      uses: vmactions/freebsd-vm@v0
      with:
        usesh: false
        sync: sshfs
        mem: 8192
        prepare: pkg install -y gmake bash python38
        run: bash -c 'export CC=/usr/bin/clang && export CXX=/usr/bin/clang++ && ./configure --openssl-no-asm --without-intl && make -j3'
    - name: Get KincTools_freebsd_x64
      run: git clone https://github.com/Kode/KincTools_freebsd_x64.git
    - name: Copy binary
      run: cp out/Release/node KincTools_freebsd_x64/kmake
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      id: commit
      continue-on-error: true
      run: |
        git -C KincTools_freebsd_x64 add .
        git -C KincTools_freebsd_x64 commit -a -m "Update kmake binary to $GITHUB_SHA."
    - name: Tag binary
      if: steps.commit.outcome == 'success'
      run: git -C KincTools_freebsd_x64 tag kmake_$GITHUB_SHA
    - name: Push binary
      id: push1
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git -C KincTools_freebsd_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KincTools_freebsd_x64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
    - name: Pull
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      run: git -C KincTools_freebsd_x64 pull --no-rebase
    - name: Push binary again
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      continue-on-error: true
      run: git -C KincTools_freebsd_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KincTools_freebsd_x64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
