name: Linux

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup latest Alpine Linux
      id: alpine-target
      uses: jirutka/setup-alpine@v1
      with:
        packages: >
          build-base
          python3
          py3-setuptools
          wget
          linux-headers
          git
          bash
          clang

    - name: Build in Alpine chroot
      env:
        CC: clang
        CXX: clang++
        LD: ld.lld
        AR: llvm-ar
      run: |
        cd /home/runner/work/kmake/kmake
        ./configure --openssl-no-asm --without-intl --fully-static --use_clang
        make -j$(nproc)
      shell: alpine.sh --root {0}

    - name: Get KoreTools_linux_x64
      run: git clone https://github.com/Kode/KoreTools_linux_x64.git
    - name: Copy binary
      run: cp /home/runner/work/kmake/kmake/out/Release/node KoreTools_linux_x64/kmake
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Add binary
      run: git -C KoreTools_linux_x64 add .
    - name: Commit binary
      id: commit
      continue-on-error: true
      run: git -C KoreTools_linux_x64 commit -a -m "Update kmake binary to $GITHUB_SHA."
    - name: Tag binary
      if: steps.commit.outcome == 'success'
      run: git -C KoreTools_linux_x64 tag kmake_$GITHUB_SHA
    - name: Push binary
      id: push1
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git -C KoreTools_linux_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_linux_x64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
    - name: Pull
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      run: git -C KoreTools_linux_x64 pull --no-rebase
    - name: Push binary again
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      continue-on-error: true
      run: git -C KoreTools_linux_x64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_linux_x64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}


  build-aarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@v1
      with:
        packages: >
          build-base
          python3
          py3-setuptools
          wget
          linux-headers
          git
          bash

    - name: Download and extract musl
      working-directory: /home/runner/work
      run: |
        wget http://kode.tech/aarch64-linux-musl-cross.tgz
        tar --extract --preserve-permissions --file aarch64-linux-musl-cross.tgz

    - name: Build in Alpine chroot
      run: |
        export PATH=$PATH:/home/runner/work/aarch64-linux-musl-cross/bin
        cd /home/runner/work/kmake/kmake
        mkdir install
        CC=aarch64-linux-musl-gcc CXX=aarch64-linux-musl-g++ CC_host=gcc CXX_host=g++ ./configure --prefix=install --dest-cpu=arm64 --cross-compiling --dest-os=linux --openssl-no-asm --without-intl --fully-static
        make -j$(nproc)
      shell: alpine.sh --root {0}

    - name: Get KoreTools_linux_arm64
      run: git clone https://github.com/Kode/KoreTools_linux_arm64.git
    - name: Copy binary
      run: cp /home/runner/work/kmake/kmake/out/Release/node KoreTools_linux_arm64/kmake
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      id: commit
      continue-on-error: true
      run: |
        git -C KoreTools_linux_arm64 add .
        git -C KoreTools_linux_arm64 commit -a -m "Update kmake binary to $GITHUB_SHA."
    - name: Tag binary
      if: steps.commit.outcome == 'success'
      run: git -C KoreTools_linux_arm64 tag linuxaarch64_$GITHUB_SHA
    - name: Push binary
      id: push1
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git -C KoreTools_linux_arm64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_linux_arm64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
    - name: Pull
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      run: git -C KoreTools_linux_arm64 pull --no-rebase
    - name: Push binary again
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      continue-on-error: true
      run: git -C KoreTools_linux_arm64 push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_linux_arm64.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}


  build-armv7l:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup latest Alpine Linux
      uses: jirutka/setup-alpine@v1
      with:
        arch: x86
        packages: >
          build-base
          python3
          py3-setuptools
          wget
          linux-headers
          git
          bash

    - name: Download and extract musl
      working-directory: /home/runner/work
      run: |
        wget http://kode.tech/armv7l-linux-musleabihf-cross.tgz
        tar --extract --preserve-permissions --file armv7l-linux-musleabihf-cross.tgz

    - name: Build in Alpine chroot
      env:
        SYSROOT: /home/runner/work/armv7l-linux-musleabihf-cross/armv7l-linux-musleabihf
        CC: clang
        CXX: clang++
        LD: ld.lld
        CFLAGS:  --target=armv7l-linux-musleabihf --sysroot=$SYSROOT
        CXXFLAGS: ${{ env.CFLAGS }}
        LDFLAGS: --target=armv7l-linux-musleabihf --sysroot=$SYSROOT -static -fuse-ld=lld
        AR:  armv7l-linux-musleabihf-ar
        NM:  armv7l-linux-musleabihf-nm
      run: |
        export PATH=$PATH:/home/runner/work/armv7l-linux-musleabihf-cross/bin
        cd /home/runner/work/kmake/kmake
        mkdir install
        ./configure --prefix=install --dest-cpu=arm --cross-compiling --dest-os=linux --openssl-no-asm --without-intl --fully-static --use_clang
        make -j$(nproc)
      shell: alpine.sh --root {0}

    - name: Get KoreTools_linux_arm
      run: git clone https://github.com/Kode/KoreTools_linux_arm.git
    - name: Copy binary
      run: cp /home/runner/work/kmake/kmake/out/Release/node KoreTools_linux_arm/kmake
    - name: Set name
      run: git config --global user.name "Robbot"
    - name: Set email
      run: git config --global user.email "robbot2019@robdangero.us"
    - name: Commit binary
      id: commit
      continue-on-error: true
      run: |
        git -C KoreTools_linux_arm add .
        git -C KoreTools_linux_arm commit -a -m "Update kmake binary to $GITHUB_SHA."
    - name: Tag binary
      if: steps.commit.outcome == 'success'
      run: git -C KoreTools_linux_arm tag kmake_$GITHUB_SHA
    - name: Push binary
      id: push1
      if: steps.commit.outcome == 'success'
      continue-on-error: true
      run: git -C KoreTools_linux_arm push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_linux_arm.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
    - name: Pull
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      run: git -C KoreTools_linux_arm pull --no-rebase
    - name: Push binary again
      if: steps.commit.outcome == 'success' && steps.push1.outcome != 'success'
      continue-on-error: true
      run: git -C KoreTools_linux_arm push https://Kode-Robbot:$ROBBOT_PASS@github.com/Kode/KoreTools_linux_arm.git main --tags
      env:
        ROBBOT_PASS: ${{ secrets.ROBBOT_PASS }}
